import type {Metadata} from 'next'
import localFont from 'next/font/local'
import React from 'react'
import './globals.css'

// https://rastikerdar.github.io/vazirmatn/fa/docs/Vazirmatn-Variable-fa
const vazirFont = localFont({
  src: '../assets/fonts/Vazirmatn-RD[wght].woff2',
  weight: '100 900',
  style: 'normal',
  display: 'swap',
  adjustFontFallback: false, // Don't automatically set a fallback font (other than them that we set)
  fallback: ['"Vazirmatn RD"', 'Vazirmatn', 'Vazir', 'Roboto'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={`${vazirFont.className} antialiased`}>{children}</body>
    </html>
  )
}
